version: "3.8"

services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-server
    restart: always
    environment:
      - WG_HOST=vm_host
      - PASSWORD=pd
    volumes:
      - ./data:/etc/wg-easy
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1